# Generated by Django 2.2 on 2019-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190205_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid_ing',
            name='s_time',
            field=models.DateTimeField(null=True),
        ),
    ]
