# Generated by Django 2.2 on 2019-02-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20190205_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid_ing',
            name='poke',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='map.raid'),
        ),
    ]
