# Generated by Django 2.2 on 2019-02-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20190205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid_ing',
            name='poke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='map.raid'),
        ),
    ]
