# Generated by Django 2.2 on 2019-02-05 07:55

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190205_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
