# Generated by Django 2.2 on 2019-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_gym_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid_ing',
            name='p_time',
            field=models.DateTimeField(null=True),
        ),
    ]
