# Generated by Django 2.2 on 2019-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_raid_ing_p_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid_ing',
            old_name='p_time',
            new_name='p_time_1',
        ),
        migrations.AddField(
            model_name='raid_ing',
            name='p_time_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='raid_ing',
            name='p_time_3',
            field=models.DateTimeField(null=True),
        ),
    ]
