# Generated by Django 2.2 on 2019-02-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20190205_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid_ing',
            name='p_time_1',
        ),
        migrations.RemoveField(
            model_name='raid_ing',
            name='p_time_2',
        ),
        migrations.RemoveField(
            model_name='raid_ing',
            name='p_time_3',
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateTimeField(null=True)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.raid_ing')),
            ],
        ),
    ]
