# Generated by Django 2.2 on 2019-02-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20190206_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid_ing',
            name='tier',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='raid_ing',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='map.gym'),
        ),
    ]
