# Generated by Django 2.2 on 2019-02-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20190207_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid_ing',
            name='tier',
        ),
        migrations.AlterField(
            model_name='raid',
            name='Tier',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
