# Generated by Django 2.1.5 on 2019-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid_ing',
            name='tier',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
