# Generated by Django 2.1.5 on 2019-02-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20190224_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid_ing',
            name='poke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.raid'),
        ),
    ]
